name: SoulAuction
version: '1.0'
main: bm.b0b0b0.soulAuction.SoulAuction
api-version: '1.21'
folia-supported: true
authors: [ b0b0b0 ]
softdepend: [ Vault, PlayerPoints, PlaceholderAPI, CoinsEngine ]
libraries:
  - net.elytrium:serializer:1.1.1
  - com.google.code.gson:gson:2.11.0
  - com.zaxxer:HikariCP:5.1.0
  - com.mysql:mysql-connector-j:8.4.0
  - org.xerial:sqlite-jdbc:3.46.0.0
  - redis.clients:jedis:5.2.0
commands:
  ah:
    description: Open auction menu
    usage: /ah [auctionId|search|page|view|selling|expired|purchased|history|sell|my|claim|cancel|limit|purge|admin|reload]
    aliases: [ax]
permissions:
  soulauction.command.ah:
    default: true
  soulauction.command.sell:
    default: true
  soulauction.command.my:
    default: true
  soulauction.command.claim:
    default: true
  soulauction.command.view:
    default: true
  soulauction.command.cancel.any:
    default: op
  soulauction.command.limit:
    default: op
  soulauction.command.reload:
    default: op
  soulauction.command.admin:
    default: op
  soulauction.priority.1:
    default: false
    description: Higher listing sort priority (use soulauction.priority.N)
