package bm.b0b0b0.soulAuction.config;

import bm.b0b0b0.soulAuction.config.settings.AuctionSettings;
import bm.b0b0b0.soulAuction.model.StorageMode;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import org.bukkit.configuration.file.YamlConfiguration;

public final class StorageRuntimeMeta {

    private static final String FILE_NAME = "storage-runtime.yml";

    private static final String FILE_HEADER = """
            DO NOT EDIT THIS FILE — SOULAUCTION INTERNAL STATE.
            THE PLUGIN OVERWRITES IT ON EVERY CLEAN SHUTDOWN AND AFTER LOAD.
            EDITING IT BREAKS STORAGE CHANGE DETECTION AND CAN HIDE DATA LOSS.
            CHANGE storage.mode ONLY IN config.yml WITH THE SERVER FULLY STOPPED.
            NOT THE PLUGIN DEVELOPER? DO NOT TOUCH THIS FILE — HANDS OFF.
            ONLY EDIT IF THE PLUGIN DEVELOPER EXPLICITLY TOLD YOU TO.
            """;

    private StorageRuntimeMeta() {
    }

    public record Snapshot(String mode, String flatDirectory, String sqliteFile, long savedAtEpochMillis) {
    }

    public record ChangeCheck(boolean configChanged, Snapshot previous, Snapshot current) {
    }

    public static Path metaPath(Path dataFolder) {
        return dataFolder.resolve("data").resolve(FILE_NAME);
    }

    public static Snapshot read(Path dataFolder) {
        Path file = metaPath(dataFolder);
        if (!Files.isRegularFile(file)) {
            return null;
        }
        YamlConfiguration yaml = YamlConfiguration.loadConfiguration(file.toFile());
        String mode = yaml.getString("mode");
        if (mode == null || mode.isBlank()) {
            return null;
        }
        return new Snapshot(
                mode.trim().toUpperCase(),
                nullToEmpty(yaml.getString("flat-directory")),
                nullToEmpty(yaml.getString("sqlite-file")),
                yaml.getLong("saved-at", 0L)
        );
    }

    public static Snapshot fromSettings(AuctionSettings settings) {
        return new Snapshot(
                StorageMode.fromString(settings.storage.mode).name(),
                settings.storage.flatDirectory == null ? "" : settings.storage.flatDirectory.trim(),
                settings.storage.database.sqliteFile == null ? "" : settings.storage.database.sqliteFile.trim(),
                System.currentTimeMillis()
        );
    }

    public static ChangeCheck compare(Path dataFolder, AuctionSettings settings) {
        Snapshot current = fromSettings(settings);
        Snapshot previous = read(dataFolder);
        if (previous == null) {
            return new ChangeCheck(false, null, current);
        }
        boolean modeChanged = !previous.mode().equalsIgnoreCase(current.mode());
        boolean flatChanged = affectsFlatStorage(previous.mode()) && affectsFlatStorage(current.mode())
                && !previous.flatDirectory().equals(current.flatDirectory());
        boolean sqliteChanged = isSqliteMode(previous.mode()) && isSqliteMode(current.mode())
                && !previous.sqliteFile().equals(current.sqliteFile());
        return new ChangeCheck(modeChanged || flatChanged || sqliteChanged, previous, current);
    }

    public static void write(Path dataFolder, AuctionSettings settings) {
        Snapshot snapshot = fromSettings(settings);
        Path file = metaPath(dataFolder);
        try {
            Files.createDirectories(file.getParent());
            YamlConfiguration yaml = new YamlConfiguration();
            yaml.set("mode", snapshot.mode());
            yaml.set("flat-directory", snapshot.flatDirectory());
            yaml.set("sqlite-file", snapshot.sqliteFile());
            yaml.set("saved-at", snapshot.savedAtEpochMillis());
            Path temp = Files.createTempFile("soulauction-storage-runtime", ".yml");
            try {
                yaml.save(temp.toFile());
                Files.writeString(
                        file,
                        fileHeaderComments() + Files.readString(temp, StandardCharsets.UTF_8),
                        StandardCharsets.UTF_8
                );
            } finally {
                Files.deleteIfExists(temp);
            }
        } catch (IOException ignored) {
        }
    }

    private static String fileHeaderComments() {
        StringBuilder output = new StringBuilder();
        for (String line : FILE_HEADER.strip().split("\n")) {
            String trimmed = line.trim();
            if (!trimmed.isEmpty()) {
                output.append("# ").append(trimmed).append('\n');
            }
        }
        output.append('\n');
        return output.toString();
    }

    private static boolean affectsFlatStorage(String modeName) {
        StorageMode mode = StorageMode.fromString(modeName);
        return mode == StorageMode.JSON || mode == StorageMode.YAML;
    }

    private static boolean isSqliteMode(String modeName) {
        return StorageMode.fromString(modeName) == StorageMode.SQLITE;
    }

    private static String nullToEmpty(String value) {
        return value == null ? "" : value.trim();
    }
}
